### ISSUE TITLE
Design of the global interface

### ISSUE THREAD

**Issue by itsrifat** [mtpain/vwplatform#5]
This issue is opened to discuss the design of the interface

**Comment by itsrifat** [comment]
@mtpain have you given thoughts on using any boilerplate HTML5 / CSS frameworks like Twitter Bootstrap for the design? that would make life lot easier I guess. We won't have to worry about cross browser support, different screen size support those kinds of things.

**Comment by mt-digital** [comment]
Yes, I think that would be great. If you want to take that on, please do, and assign yourself to this issue. I have done some weird stuff to build the search result view. I changed the title of this to "design of the global interface" because I think some other things will need to be done with the search interface specifically, and I'd like to keep those changes separate.

**Comment by mt-digital** [comment]
This is GSToRE's data browsing view: http://dev.nmepscor.org/data_portal/browse-data

**Comment by mt-digital** [comment]
Done with  #14
